- styles.css
Relate #5
Add styles.css file with initial styling for navigation bar
> style: add styles.css with styles for navbar

- index.html
Created the forms. No styling yet.
> Created contact and newsletter forms

- index.html
- styles.css
Relates #5
First pass at navbar and header - WIP sharing for styles sheet link and font
> chore: initial navbar and styles

- index.html
- styles.css
Forms are styled but lacking colour.
> Styled Forms

- index.html
- styles.css
Check that the events container is okay.
> Fix the CSS for the event-container section

- index.html
- styles.css
I gave the Navbar some margin left/right to make it more focused. Also positioned the header text a bit better + changed the colours to match the pallet. Made a bit more responsive too
> Cleaned up header and made more responsive.

- index.html
- script/main.js
> feat: javascript generating event cards and rendering to browser

- data/team.json
> feat: pushing team photos and filepaths into json

- index.html
- script/contact-form.js
- script/newsletter-form.js
- styles.css
Both contact and newsletter forms store input data to local storage.
> forms now store data to local storage

- index.html
- styles.css
> feat: add home section

- index.html
fixed the spelling in the header tagline
> change-in-the-header-tagline

- script/main.js
- styles/event-cards.css
- styles/team-cards.css
> fix: cards styles css

- styles/root.css
> fix: event headings and paragraph style

- styles/footer.css
changed the gap between the logos in the footer as well as filling the rest of the space with the background colour and making sure there was no white gaps
> improved-footer

- index.html
- styles/footer.css
changed the styling of the header and reduced gap between title and logo
> Change from p to h2

- data/team.json
- index.html
> chore: add profiles and tagline

- script/README.md
- script/contact-form.js
- script/newsletter-form.js
> docs: added javascript documentation

- index.html
- styles/footer.css
added a trademark. made the icons larger and added some css styling to make page look better
> Trademark and icon size

- script/main.js
With the two dots in front of the /data, the link that was uploading was wrong. 
instead of https://fac30.github.io/Pro01_Max_Itzi_Josh_Riley/data, it was loading https://fac30.github.io/data
It should work now!
> Remove the two dots in line 5 of JS file

- script/main.js
Sorry I needed to leave one dot, I think it definitely works now
> Add one dot in line 5 of JS file

- data/team.json
> fix: pdate team.json
